// Generated by tools/generate_standalone_processor.py.
#include "trajectory_tracking_processor.hh"
#include "smc_controller.hh"
#include <algorithm>
#include <cstddef>
#include <stdexcept>
#include <string>

#include <pybind11/eigen.h>
#include <pybind11/numpy.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;
using Processor = TrajectoryTrackingProcessor;

namespace
{
Processor::VectorMap VectorMapFromDict(const py::dict &source)
{
    Processor::VectorMap result;
    for (const auto &item : source)
    {
        result.emplace(
            py::cast<std::string>(item.first),
            py::cast<Eigen::VectorXf>(item.second));
    }
    return result;
}

void UpdateVectorDict(
    py::dict target, const Processor::VectorMap &source)
{
    for (const auto &[key, vector] : source)
    {
        const py::str python_key(key);
        bool updated_existing_array = false;
        if (target.contains(python_key))
        {
            const py::handle existing = target[python_key];
            if (py::isinstance<py::array>(existing))
            {
                py::array array = py::reinterpret_borrow<py::array>(existing);
                const bool compatible =
                    array.dtype().is(py::dtype::of<float>()) &&
                    array.ndim() == 1 &&
                    array.shape(0) == vector.size() &&
                    (array.flags() & py::array::c_style) != 0 &&
                    array.writeable();
                if (compatible)
                {
                    std::copy(
                        vector.data(), vector.data() + vector.size(),
                        static_cast<float *>(array.mutable_data()));
                    updated_existing_array = true;
                }
            }
        }
        if (!updated_existing_array)
        {
            target[python_key] = py::cast(vector);
        }
    }
}
} // namespace

PYBIND11_MODULE(bindings, module)
{
    module.doc() =
        "Standalone processor with in-place Python output dictionaries.";

    py::class_<Processor>(module, "TrajectoryTrackingProcessor")
        .def(
            py::init<
                std::string,
                bool,
                int,
                int,
                const std::vector<float> &,
                const std::vector<float> &,
                int,
                float,
                float,
                float,
                float,
                float,
                float,
                float,
                float,
                float,
                float,
                float,
                float,
                float,
                int,
                std::uint32_t
            >(),
            py::arg("state_key"),
            py::arg("use_rotation_matrix"),
            py::arg("state_history_len"),
            py::arg("future_waypoint_num"),
            py::arg("action_scaling"),
            py::arg("action_bias"),
            py::arg("physics_steps_per_control"),
            py::arg("physics_dt"),
            py::arg("horizontal_amplitude_min"),
            py::arg("horizontal_amplitude_max"),
            py::arg("vertical_amplitude_min"),
            py::arg("vertical_amplitude_max"),
            py::arg("height_offset_min"),
            py::arg("height_offset_max"),
            py::arg("trajectory_speed_min"),
            py::arg("trajectory_speed_max"),
            py::arg("maximum_normal_acceleration"),
            py::arg("vertical_position_weight"),
            py::arg("vertical_velocity_weight"),
            py::arg("fixed_zero_yaw_probability"),
            py::arg("trajectory_sampling_attempts"),
            py::arg("trajectory_seed"))
        .def("update_trajectory", &TrajectoryTrackingProcessor::UpdateTrajectory)
        .def("reset", &TrajectoryTrackingProcessor::Reset, py::arg("initial_state"))
        .def(
            "process_observation",
            [](Processor &self,
               const Processor::StateMap &current_state,
               const Processor::StateMap &current_state_dot,
               const Processor::StateMap &previous_state,
               const Processor::StateMap &previous_state_dot,
               py::dict processed_observation)
            {
                Processor::VectorMap output =
                    VectorMapFromDict(processed_observation);
                {
                    py::gil_scoped_release release;
                    self.ProcessObservation(
                        current_state, current_state_dot, previous_state,
                        previous_state_dot, output);
                }
                UpdateVectorDict(processed_observation, output);
            },
            py::arg("current_state"), py::arg("current_state_dot"),
            py::arg("previous_state"), py::arg("previous_state_dot"),
            py::arg("processed_observation"))
        .def(
            "process_action",
            [](Processor &self, py::dict policy_action,
               py::dict processed_action)
            {
                const Processor::VectorMap input =
                    VectorMapFromDict(policy_action);
                Processor::VectorMap output =
                    VectorMapFromDict(processed_action);
                {
                    py::gil_scoped_release release;
                    self.ProcessAction(input, output);
                }
                UpdateVectorDict(processed_action, output);
            },
            py::arg("policy_action"), py::arg("processed_action"))
        .def_property_readonly("observation_dimension", &TrajectoryTrackingProcessor::ObservationDimension)
        .def("reference_state", &TrajectoryTrackingProcessor::ReferenceState)
        .def("reference_state_at", &TrajectoryTrackingProcessor::ReferenceStateAt, py::arg("time"))
        .def_property_readonly("current_time", &TrajectoryTrackingProcessor::CurrentTime);
       
       py::class_<SlidingModeController>(module, "SlidingModeController")
        .def(py::init<Eigen::Vector3d,
                          Eigen::Vector3d , 
                          Eigen::Vector3d ,
                          Eigen::Vector3d ,    
                          Eigen::Vector3d , 
                          Eigen::Vector3d ,
                          Eigen::Vector3d ,
                          Eigen::Vector3d ,
                          double ,
                          Eigen::Matrix3d >())
         .def("calculate_moments", &SlidingModeController::calculate_moments)
         .def("calculate_force", &SlidingModeController::calculate_force);
}
